"""add description to products

Revision ID: 1373a6d84643
Revises: 5ba8a0fc06ef
Create Date: 2021-12-22 13:01:19.291420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1373a6d84643'
down_revision = '5ba8a0fc06ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
